### PR TITLE
Simple test for secret entry

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
Used in [ALKiln#536](https://github.com/SuffolkLITLab/ALKiln/pull/536). 

Just a simple text entry test. A bit hand tailored to the feature test. I would have tried to use an existing test, but there didn't seem to be any that had text entry that didn't also have heavy / slow features like file upload before.

### CODE REVIEW

**Review by plocket — APPROVED** [review]
Looks good! It may be worth renaming this for its current purpose sometime. Something about secrets. [That is, I think secrets having their own test interview is reasonable and we can name this one to match.] Our convention is to use a `code` block, but it's something we can certainly discuss. Merge when you feel comfortable.

**Comment by plocket** [comment]
We could also split up our tests a bit, which I've been thinking can be a good move. This file could actually do double duty to test text entry fields as well. It would be at some point in the future because it needs a couple more features to work for that purpose.

**Comment by plocket** [comment]
Noticing now the name is "text_texts", so it'll need to be updated sometime in the future anyway. Sorry I missed that.

**Comment by plocket** [comment]
Ready for review @BryceStevenWilley

**Comment by BryceStevenWilley** [comment]
Just realized I can't approve my own request, but LGTM!

**Pull request merged**
